### ISSUE TITLE
visRemoveEdges documentation

### ISSUE THREAD

**Issue by hxrts** [datastorm-open/visNetwork#132]
help files for ```visRemoveEdges``` reads as follows

```
Usage:

     visRemoveEdges(graph, id)

Arguments:

   graph: : a ‘visNetworkProxy’ object
      id: : vector of id, edges to remove
```

I'm not quite sure how to read this. Edges don't have their own ids, I've tried removing node ids for those edges as well as giving this function a dataframe similar to updateEdges, neither seem to work. Sorry for posting a help question as a github issue, but I can't find further documentation elsewhere so it seems this man page could be filled out a a bit. Thanks!!
